name: 'CI Setup'
description: 'Install node and pnpm'
inputs:
  node_version:
    required: false
    default: v20.x
    description: 'The version of Node.js to use'
  pnpm_version:
    required: false
    default: 8
    description: 'The version of pnpm to use'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3
      name: Install pnpm
      id: pnpm-install
      with:
        version: ${{ inputs.pnpm_version }}
        run_install: false
        
    - name: Use Node ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'pnpm'


    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install dependencies
      shell: bash
      run: pnpm install

